### ISSUE TITLE
No data values are used when interpolating, giving weird results

### ISSUE THREAD

**Issue by JesseCrocker** [perliedman/node-hgt#5]

**Comment by JesseCrocker** [comment]
This probably isn't worth fixing. The right solution is to just voidfill the DEMs first.

**Comment by perliedman** [comment]
Hm, interesting. Although I never got back with a comment, this seemed like a valid thing to fix.

If we go with void fill as the workaround, it should probably be mentioned in the docs.

I'll go ahead and reopen this, to keep it on my todo to at least update the docs with a note about void fill being a requirement to get sane results!
